Added updates for languages.
WorldHealthOrganization/ls-responsepicker pull request #2
Opened 2023-03-08 19:01 UTC by cristiangirlea

Added languages for issue #92
https://github.com/HeRAMS-WHO/herams-backlog/issues/92#issuecomment-1459899705

2023-03-08 19:02 UTC, cristiangirlea commented
Note that there are missing translations for the following:
"No text found for"
"Date of update"
Also should "Response id" change to "Update id"?

2023-03-13 09:32 UTC, SamMousa requested changes

2023-03-13 09:32 UTC, SamMousa commented on ResponsePicker.php
> +            $idHeader = "Update ID";
I think this is useless; it is overridden either on line 801 or 803. Also the case in old code; so not an error you introduced. 
```suggestion
```

2023-03-13 09:32 UTC, SamMousa commented on ResponsePicker.php
> +                    content: {$this->getTranslation('New')};
Seems quotes are missing here. 
Note that we probably should escape it. Since all strings are in this code however I'm okay with not doing that.
Instead add a comment to the `getTranslation()` function that it MUST only return strings that are valid in CSS without further escaping (so cannot contain `"`).

2023-03-13 10:18 UTC, cristiangirlea commented on ResponsePicker.php
> +                    content: {$this->getTranslation('New')};
I can create a new function for this type of escaped translation, without adding extra logic on getTranslation.

2023-03-13 10:21 UTC, SamMousa commented on ResponsePicker.php
> +                    content: {$this->getTranslation('New')};
Yeah go ahead; it is a bit overkill, which is why I didn't suggest it. But on the other hand, it is better and can't hurt!

2023-03-13 12:04 UTC, merged